### ISSUE TITLE
Share Menu themed incorrectly on 8.0

### ISSUE THREAD

**Issue by Arkanoid0** [SpiritCroc/DefaultDarkTheme-oms#10]
![photo_2017-09-18_20-30-50](https://user-images.githubusercontent.com/1642129/30572051-10e3d6da-9cb1-11e7-886c-d4c04345072e.jpg)
The share menu is themed incorrectly, the selection text is not there. 

(upper portion is obfuscated for privacy)

**Comment by SpiritCroc** [comment]
Use legacy variants where possible on ROMs that don't have Substratum exposure commits (so every o8.0 ROM for now)
