### ISSUE TITLE
Default App Picker invisible

### ISSUE THREAD

**Issue by timlogemann** [SpiritCroc/DefaultDarkTheme-oms#12]
When using the default white notifications the card that allows you to pick a default application is unreadable because of white text on white background. 

I'm on a stock 8.0 nexus 6P

![As seen here](https://user-images.githubusercontent.com/15154878/31294992-2ad35284-aadd-11e7-8958-8ee54ec4fd6a.png)

**Comment by SpiritCroc** [comment]
See #10
