### ISSUE TITLE
White notification

### ISSUE THREAD

**Issue by paulbertoli94** [SpiritCroc/DefaultDarkTheme-oms#16]
https://imgur.com/gallery/7Gpgt

When i pull down the bar the notification first are white then became black, is this a bug?
on Nexus 5X with oreo 8.0

**Comment by SpiritCroc** [comment]
Are you using a dark notification variant? If yes, they aren't fully supported on Oreo yet, so this happens; once I find more time, I might look into small details like this

**Comment by SpiritCroc** [comment]
Looks fine on my devices
