### ISSUE TITLE
Android 8.0.0 with Substratum v854 & Default Dark Theme v5.2(39) choose app lower notification is white

### ISSUE THREAD

**Issue by JSylvia007** [SpiritCroc/DefaultDarkTheme-oms#18]
Howdy! This theme is excellent!   Using is on a Google Pixel 2XL with Android 8.0.0 via Andromeda and Substratum.

The only issue I have is that the bottom "Choose App" notification is all white with just the application icon. I will try to attach a screenshot. In next post.

**Comment by JSylvia007** [comment]
![screenshot_20171029-230717](https://user-images.githubusercontent.com/32574636/32152996-014ba19a-bcfe-11e7-8a93-835b2f61bb1a.png)

**Comment by SpiritCroc** [comment]
Great to hear you like it!
Please use legacy variants where possible on ROMs that don't have Substratum exposure commits (so every o8.0 ROM for now, stock ROM in any case)
