### ISSUE TITLE
Clock theme

### ISSUE THREAD

**Issue by dimqua** [SpiritCroc/DefaultDarkTheme-oms#20]
Is it possible to make the clock app greyer? Currently [it's bluish](https://i.imgur.com/CcUhIcM.png). 

I use LineageOS 14.1, for that matter.

As [an example](https://i.imgur.com/CE0hgvu.png), see [Clock+](https://f-droid.org/packages/com.philliphsu.clock2/) app.

**Comment by SpiritCroc** [comment]
I don't remember why I didn't do it, either it's hardcoded or I forgot about it; I'd prefer it grey too though. I might try again at some point so keeping this open for now

**Comment by SpiritCroc** [comment]
Unfortunately not possible on Lineage 14.1, it's hardcoded in java, see https://github.com/LineageOS/android_packages_apps_DeskClock/blob/cm-14.1/src/com/android/deskclock/Utils.java#L118

**Comment by dimqua** [comment]
Thanks for adding it anyway, who knows maybe further LOS versions will add OMS support finally.

**Comment by SpiritCroc** [comment]
The commit you're probably referring to works on Android 8.1 (also on Lineage based ROMs)
