### ISSUE TITLE
Bug - phone voicemail white circles

### ISSUE THREAD

**Issue by mrbluecoat** [SpiritCroc/DefaultDarkTheme-oms#26]
In Android 8.1 the phone voicemail displays three white circles.  Screenshot: https://ibb.co/isELip

**Comment by SpiritCroc** [comment]
Thank you for reporting!
I cannot test this right now, so will push an update to the Play Store beta channel soon, can you please report back whether version 7.7.1 fixes it?
(If you don't like Google Play tell me and I'll provide an alternative)

**Comment by mrbluecoat** [comment]
That worked, thanks!

**Comment by SpiritCroc** [comment]
Great, thanks for testing!
