### ISSUE TITLE
Brave browser support

### ISSUE THREAD

**Issue by mrbluecoat** [SpiritCroc/DefaultDarkTheme-oms#27]
A bit of a longshot, but any chance you'd add support for Brave Browser (https://brave.com)?  I haven't found a better alternative for ad-free browsing but the whiteness is blinding...

**Comment by mrbluecoat** [comment]
For now I guess I'll switch to the slower Ghostery Privacy Browser.

**Comment by SpiritCroc** [comment]
Unlikely, since I don't use it. I guess most colours you'll see in a browser are website content either way, so not touched by android themes.
