### ISSUE TITLE
no settings

### ISSUE THREAD

**Issue by ghost** [SpiritCroc/DefaultDarkTheme-oms#30]
This app has no settings, just a blank screen then click on for some information about the app...it's not doing anything...my device is Huawei mediapad m3 lite, Android 7.0

**Comment by SpiritCroc** [comment]
Default Dark is a theme for the [substratum theme engine](https://play.google.com/store/apps/details?id=projekt.substratum&hl=en_US). You can see it as an add-on to the substratum app. This means that Default Dark does not provide any functionality on its own, but only when using the substratum app.
For instructions on how to get substratum running on your device (in case your device meets the required software criteria), please refer to the [substratum documentation](https://forum.xda-developers.com/apps/substratum/official-starting-substratum-andromeda-t3798316/).

**Comment by ghost** [comment]
Okay, I'll study this...

On Tuesday, November 12, 2019, SpiritCroc <notifications@github.com> wrote:
> Default Dark is a theme for the substratum theme engine. You can see it
as an add-on to the substratum app. This means that Default Dark does not
provide any functionality on its own, but only when using the substratum
app.
> For instructions on how to get substratum running on your device (in case
your device meets the required software criteria), please refer to the
substratum documentation.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci4.googleusercontent.com/proxy/6uGbNH1yX1UxhCTihe5RJzm2tT2TgGQTwkgQhHnwJro5W-KdEV0QTlaRnGMMeQ6u0wQqAvAMiZ-0EP-wyCchOAStNyrTGjoAua-FCaSDOZ2RxyCP6ja0XltynQz-ly-jxkDZUSzu19eOyHYmVWI6q3-KRznr7nQdejGIWWLkRIMia7cqsyt4Q5UIcWPF9wL1SRCC3SmqR93OJp3Wj0hQigijcDRGQ0ifh5jmXsd5zQ=s0-d-e1-ft#https://github.com/notifications/beacon/AMHMGMNL4663BTEILXXHBFLQTKWAHA5CNFSM4JMDEX52YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOED2IA4I.gif
>

-- 
Android strong, be all you can be, end transmission.
