### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by mase76** [SpiritCroc/DefaultDarkTheme-oms#6]
Hi!
Can you add the theme to F-Droid? There are no Substratum themes in the F-Droid
Repo yet.

**Comment by SpiritCroc** [comment]
Was planning that some time ago, but forgot it then.
I like the idea, and since there is demand now, probably will do sooner or later

**Comment by new-on-github** [comment]
I would also like this. Any news about this?

**Comment by SpiritCroc** [comment]
https://gitlab.com/fdroid/rfp/issues/326#note_39309852

**Comment by new-on-github** [comment]
Thanks for your work!
