### ISSUE TITLE
[Request] AOSP keyboard theme

### ISSUE THREAD

**Issue by js803655** [SpiritCroc/DefaultDarkTheme-oms#7]

**Comment by SpiritCroc** [comment]
I looked into this before, but AOSP keyboard seems very theme-unfriendly to me, so not worth the effort in my opinion.
I won't do it, if anybody else wants to do it no problem

**Comment by dimqua** [comment]
@SpiritCroc Do you plan to support any custom keyboard instead?

**Comment by SpiritCroc** [comment]
@dimqua
No
